In [65]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [66]:
import pandas as pd

#df = pd.read_csv("/content/drive/myDrive/Colab Notebooks/dados/base_agendamentos_saude_suja.csv")
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dados/base_agendamentos_saude_suja.csv")
df.head()

  data_agendamento     paciente  especialidade      medico  turno  faltou
0       2025-01-04  Paciente_38    Ginecologia         NaN  Manhã       0
1       2025-01-18  Paciente_45    Ginecologia         NaN  manha       1
2       2025-04-25   Paciente_2    Ginecologia   Dr. Silva  manha       0
3       05-01-2025  Paciente_49  Clínico Geral  Dra. Maria  Noite       1
4       2025-03-06  Paciente_37  Clínico Geral    Dr. João  manha       1

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 157 entries, 0 to 199
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   data_agendamento        157 non-null    object
 1   paciente                157 non-null    object
 2   especialidade           157 non-null    object
 3   medico                  157 non-null    object
 4   turno                   157 non-null    object
 5   faltou                  157 non-null    int64
 6   data_agendamento_limpa  157 non-null    datetime64[ns]
 7   ano                     157 non-null    int32
 8   mes                     157 non-null    int32
 9   dia                     157 non-null    int32
 10  dia_semana              157 non-null    object
dtypes: datetime64[ns](1), int32(3), int64(1), object(6)
memory usage: 16.9+ KB

In [100]:
df.isna().sum()

data_agendamento          0
paciente                  0
especialidade             0
medico                    0
turno                     0
faltou                    0
data_agendamento_limpa    0
ano                       0
mes                       0
dia                       0
dia_semana                0
dtype: int64

In [52]:
#df.describe(include='all')
df.describe()

           faltou
count  200.000000
mean     0.540000
std      0.499648
min      0.000000
25%      0.000000
50%      1.000000
75%      1.000000
max      1.000000

In [69]:
df["data_agendamento_limpa"] = pd.to_datetime(
    df["data_agendamento"],
    errors='coerce'
)

In [77]:
df

,data_agendamento,paciente,especialidade,medico,turno,faltou,data_agendamento_limpa
0,2025-01-04,Paciente_38,Ginecologia,NaN,Manhã,0,2025-01-04
1,2025-01-18,Paciente_45,Ginecologia,NaN,Manhã,1,2025-01-18
2,2025-04-25,Paciente_2,Ginecologia,Dr. Silva,Manhã,0,2025-04-25
3,05-01-2025,Paciente_49,Clínico Geral,Dra. Maria,Noite,1,NaT
4,2025-03-06,Paciente_37,Clínico Geral,Dr. João,Manhã,1,2025-03-06
...,...,...,...,...,...,...,...
195,2025-01-11,Paciente_32,Cardiologia,NaN,NaN,0,2025-01-11
196,2025-03-30,Paciente_36,Clínico Geral,Dr. João,NaN,0,2025-03-30
197,2025-02-23,Paciente_49,Ginecologia,Dr. Silva,Noite,1,2025-02-23
198,23-02-2025,Paciente_16,NaN,Dra. Maria,Tarde,1,NaT
199,2025-02-19,Paciente_45,Clínico Geral,NaN,Manhã,1,2025-02-19

In [74]:
df['data_agendamento'] = df['data_agendamento'].str.replace('/', '-')

In [76]:
# ajustar turnos
map_turno = {
    "Manha": "Manhã",
    "Manhã": "Manhã",
    "manha": "Manhã",
    "Tarde": "Tarde",
    "Noite": "Noite",
    "None": None
}
df["turno"] = df["turno"].map(map_turno)

In [80]:
#preencher com valor padrão
df["especialidade"].fillna("Não Informado", inplace=True)
df["medico"].fillna("Não Informado", inplace=True)
#df["turno"].fillna("Não Informado", inplace=True)

In [58]:
df

,data_agendamento,paciente,especialidade,medico,turno,faltou,data_agendamento_limpa
0,2025-01-04,Paciente_38,Ginecologia,Não Informado,Manhã,0,2025-01-04
1,2025-01-18,Paciente_45,Ginecologia,Não Informado,Não Informado,1,2025-01-18
2,2025-04-25,Paciente_2,Ginecologia,Dr. Silva,Não Informado,0,2025-04-25
3,05-01-2025,Paciente_49,Clínico Geral,Dra. Maria,Noite,1,NaT
4,2025-03-06,Paciente_37,Clínico Geral,Dr. João,Não Informado,1,2025-03-06
...,...,...,...,...,...,...,...
195,2025-01-11,Paciente_32,Cardiologia,Não Informado,Não Informado,0,2025-01-11
196,2025-03-30,Paciente_36,Clínico Geral,Dr. João,Não Informado,0,2025-03-30
197,2025-02-23,Paciente_49,Ginecologia,Dr. Silva,Noite,1,2025-02-23
198,23-02-2025,Paciente_16,Não Informado,Dra. Maria,Tarde,1,NaT
199,2025-02-19,Paciente_45,Clínico Geral,Não Informado,Não Informado,1,2025-02-19

In [97]:
#criar campos uteis para analise
#df["data_agendamento_limpa"].dropna(inplace=True)
df.dropna(subset=['data_agendamento_limpa'], inplace = True)
df["ano"] = df["data_agendamento_limpa"].dt.year
df["mes"] = df["data_agendamento_limpa"].dt.month
df["dia"] = df["data_agendamento_limpa"].dt.day
df["dia_semana"] = df["data_agendamento_limpa"].dt.day_name()

In [99]:
df

,data_agendamento,paciente,especialidade,medico,turno,faltou,data_agendamento_limpa,ano,mes,dia,dia_semana
0,2025-01-04,Paciente_38,Ginecologia,Não Informado,Manhã,0,2025-01-04,2025,1,4,Saturday
1,2025-01-18,Paciente_45,Ginecologia,Não Informado,Manhã,1,2025-01-18,2025,1,18,Saturday
2,2025-04-25,Paciente_2,Ginecologia,Dr. Silva,Manhã,0,2025-04-25,2025,4,25,Friday
4,2025-03-06,Paciente_37,Clínico Geral,Dr. João,Manhã,1,2025-03-06,2025,3,6,Thursday
5,2025-04-02,Paciente_25,Cardiologia,Não Informado,Tarde,1,2025-04-02,2025,4,2,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...
194,2025-02-04,Paciente_27,Cardiologia,Dr. João,Manhã,1,2025-02-04,2025,2,4,Tuesday
195,2025-01-11,Paciente_32,Cardiologia,Não Informado,Não Informado,0,2025-01-11,2025,1,11,Saturday
196,2025-03-30,Paciente_36,Clínico Geral,Dr. João,Não Informado,0,2025-03-30,2025,3,30,Sunday
197,2025-02-23,Paciente_49,Ginecologia,Dr. Silva,Noite,1,2025-02-23,2025,2,23,Sunday
199,2025-02-19,Paciente_45,Clínico Geral,Não Informado,Manhã,1,2025-02-19,2025,2,19,Wednesday